#include <stdlib.h>
#include <string.h>

#include "rdktr.h"
#include "rdktr_internal.h"

/* Embedded default rule set, generated by Scripts/compile_rules.py. */
extern const uint8_t rdktr_default_rules_data[];
extern const size_t rdktr_default_rules_size;

static uint32_t rd32(const uint8_t *p) {
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

/* offset/size pair fits into the blob, is 4-byte aligned */
static int section_ok(size_t blob_size, uint32_t off, uint64_t bytes) {
    if (off % 4 != 0) return 0;
    if ((uint64_t)off + bytes > blob_size) return 0;
    return 1;
}

rdktr_engine *rdktr_create(const void *blob_ptr, size_t size) {
    const uint8_t *blob = (const uint8_t *)blob_ptr;
    if (!blob || size < RDKTR_HEADER_SIZE) return NULL;
    if (((uintptr_t)blob) % 4 != 0) return NULL;
    if (memcmp(blob, "RDK1", 4) != 0) return NULL;
    if (rd32(blob + 4) != RDKTR_VERSION) return NULL;

    uint32_t total_size = rd32(blob + 8);
    if (total_size < RDKTR_HEADER_SIZE || total_size > size) return NULL;

    rdktr_engine e;
    memset(&e, 0, sizeof(e));
    e.blob = blob;
    e.blob_size = total_size;

    e.rule_count = rd32(blob + 12);
    uint32_t rules_off = rd32(blob + 16);
    uint32_t strpool_off = rd32(blob + 20);
    e.strpool_size = rd32(blob + 24);
    e.dat_size = rd32(blob + 28);
    uint32_t dat_base_off = rd32(blob + 32);
    uint32_t dat_check_off = rd32(blob + 36);
    uint32_t dat_word_id_off = rd32(blob + 40);
    uint32_t dat_prefix_pat_off = rd32(blob + 44);
    e.pat_count = rd32(blob + 48);
    uint32_t pat_off = rd32(blob + 52);
    uint32_t pat_rules_off = rd32(blob + 56);
    e.pat_rules_count = rd32(blob + 60);
    e.ac_state_count = rd32(blob + 64);
    uint32_t ac_states_off = rd32(blob + 68);
    uint32_t ac_trans_off = rd32(blob + 72);
    e.ac_trans_count = rd32(blob + 76);
    uint32_t ac_out_off = rd32(blob + 80);
    e.ac_out_count = rd32(blob + 84);
    e.max_phrase_len = rd32(blob + 88);
    e.comma_rule_id = rd32(blob + 92);
    e.comma_threshold = rd32(blob + 96);

    if (!section_ok(total_size, rules_off, (uint64_t)e.rule_count * 12)) return NULL;
    if (!section_ok(total_size, strpool_off, e.strpool_size)) return NULL;
    if (e.strpool_size == 0) return NULL;
    if (blob[strpool_off + e.strpool_size - 1] != '\0') return NULL;
    if (e.dat_size == 0) return NULL;
    if (!section_ok(total_size, dat_base_off, (uint64_t)e.dat_size * 4)) return NULL;
    if (!section_ok(total_size, dat_check_off, (uint64_t)e.dat_size * 4)) return NULL;
    if (!section_ok(total_size, dat_word_id_off, (uint64_t)e.dat_size * 4)) return NULL;
    if (!section_ok(total_size, dat_prefix_pat_off, (uint64_t)e.dat_size * 4)) return NULL;
    if (!section_ok(total_size, pat_off, (uint64_t)e.pat_count * 8)) return NULL;
    if (!section_ok(total_size, pat_rules_off, (uint64_t)e.pat_rules_count * 4)) return NULL;
    if (e.ac_state_count == 0) return NULL;
    if (!section_ok(total_size, ac_states_off, (uint64_t)e.ac_state_count * 20)) return NULL;
    if (!section_ok(total_size, ac_trans_off, (uint64_t)e.ac_trans_count * 8)) return NULL;
    if (!section_ok(total_size, ac_out_off, (uint64_t)e.ac_out_count * 8)) return NULL;
    if (e.max_phrase_len == 0 || e.max_phrase_len > 1024) return NULL;
    if (e.comma_rule_id != RDKTR_NONE && e.comma_rule_id >= e.rule_count) return NULL;

    e.rules = (const rdktr_rule_entry *)(blob + rules_off);
    e.strpool = (const char *)(blob + strpool_off);
    e.dat_base = (const uint32_t *)(blob + dat_base_off);
    e.dat_check = (const uint32_t *)(blob + dat_check_off);
    e.dat_word_id = (const uint32_t *)(blob + dat_word_id_off);
    e.dat_prefix_pat = (const uint32_t *)(blob + dat_prefix_pat_off);
    e.pats = (const rdktr_pattern_entry *)(blob + pat_off);
    e.pat_rules = (const uint32_t *)(blob + pat_rules_off);
    e.ac_states = (const rdktr_ac_state *)(blob + ac_states_off);
    e.ac_trans = (const rdktr_ac_trans *)(blob + ac_trans_off);
    e.ac_out = (const rdktr_ac_out *)(blob + ac_out_off);

    /* cross-references */
    for (uint32_t i = 0; i < e.rule_count; i++) {
        if (e.rules[i].title_off >= e.strpool_size) return NULL;
        if (e.rules[i].desc_off >= e.strpool_size) return NULL;
    }
    for (uint32_t i = 0; i < e.pat_count; i++) {
        uint64_t end = (uint64_t)e.pats[i].rules_start + e.pats[i].rules_count;
        if (end > e.pat_rules_count) return NULL;
    }
    for (uint32_t i = 0; i < e.pat_rules_count; i++) {
        if (e.pat_rules[i] >= e.rule_count) return NULL;
    }
    for (uint32_t i = 0; i < e.ac_state_count; i++) {
        const rdktr_ac_state *s = &e.ac_states[i];
        if ((uint64_t)s->trans_start + s->trans_count > e.ac_trans_count) return NULL;
        if ((uint64_t)s->out_start + s->out_count > e.ac_out_count) return NULL;
        if (s->fail >= e.ac_state_count) return NULL;
    }
    for (uint32_t i = 0; i < e.ac_trans_count; i++) {
        if (e.ac_trans[i].next >= e.ac_state_count) return NULL;
    }
    for (uint32_t i = 0; i < e.ac_out_count; i++) {
        if (e.ac_out[i].pattern_id >= e.pat_count) return NULL;
        if (e.ac_out[i].tok_len == 0 || e.ac_out[i].tok_len > e.max_phrase_len)
            return NULL;
    }
    for (uint32_t i = 0; i < e.dat_size; i++) {
        if (e.dat_check[i] != RDKTR_NONE && e.dat_check[i] >= e.dat_size) return NULL;
        if (e.dat_prefix_pat[i] != RDKTR_NONE && e.dat_prefix_pat[i] >= e.pat_count)
            return NULL;
    }

    rdktr_engine *out = (rdktr_engine *)malloc(sizeof(rdktr_engine));
    if (!out) return NULL;
    *out = e;
    return out;
}

rdktr_engine *rdktr_create_default(void) {
    return rdktr_create(rdktr_default_rules_data, rdktr_default_rules_size);
}

void rdktr_destroy(rdktr_engine *engine) { free(engine); }

uint32_t rdktr_rule_count(const rdktr_engine *engine) {
    return engine ? engine->rule_count : 0;
}

const char *rdktr_rule_title(const rdktr_engine *engine, uint32_t rule_id) {
    if (!engine || rule_id >= engine->rule_count) return NULL;
    return engine->strpool + engine->rules[rule_id].title_off;
}

const char *rdktr_rule_description(const rdktr_engine *engine, uint32_t rule_id) {
    if (!engine || rule_id >= engine->rule_count) return NULL;
    return engine->strpool + engine->rules[rule_id].desc_off;
}

uint32_t rdktr_rule_weight(const rdktr_engine *engine, uint32_t rule_id) {
    if (!engine || rule_id >= engine->rule_count) return 0;
    return engine->rules[rule_id].weight;
}
