"""Serialization of a compiled ruleset into the binary blob format."""
from pathlib import Path

import struct

from .compiler import Compiler
from .constants import ELEM_GAP, ELEM_PUNCT, ELEM_WORD, HEADER_SIZE, MAGIC, VERSION
from .trie import Trie


C_HEADER = """\
/* Generated by scripts/compile_rules.py — do not edit by hand.
 * Regenerate with: python3 scripts/compile_rules.py
 */
#include "rdktr_internal.h"
"""

C_FOOTER = """\
const rdktr_embedded_ruleset rdktr_embedded_rulesets[] = {{
{entries}
}};

const size_t rdktr_embedded_ruleset_count = {count};
"""

def emit_c(blobs: list[tuple[str, bytes]], path: Path) -> None:
    parts = [C_HEADER]
    for lang, blob in blobs:
        rows = []
        for i in range(0, len(blob), 16):
            chunk = blob[i : i + 16]
            rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        parts.append(
            f"\n_Alignas(4) static const uint8_t rules_{lang}[] = {{\n"
            + "\n".join(rows)
            + "\n};\n"
        )
    entries = "\n".join(
        f'    {{"{lang}", rules_{lang}, sizeof(rules_{lang})}},' for lang, _ in blobs
    )
    parts.append("\n" + C_FOOTER.format(entries=entries, count=len(blobs)))
    path.write_text("".join(parts), encoding="utf-8")


def build_blob(comp: Compiler) -> bytes:
    """Serialize a filled Compiler into a binary blob; sets comp.stats."""
    # word trie: exact words and prefix stems share it
    trie = Trie()
    for word, wid in comp.word_ids.items():
        trie.insert_word(word, wid)
    for stem, pid in comp.prefix_ids.items():
        trie.insert_prefix(stem, pid)
    base, check, wid_arr, pfx_arr = trie.build_double_array()

    # self-check: every word and prefix must be reachable
    for word, wid in comp.word_ids.items():
        slot = Trie.lookup(base, check, word.encode("utf-8"))
        assert slot is not None and wid_arr[slot] == wid, f"DAT broken for {word!r}"
    for stem, pid in comp.prefix_ids.items():
        slot = Trie.lookup(base, check, stem.encode("utf-8"))
        assert slot is not None and pfx_arr[slot] == pid

    # string pool (deduplicated, NUL-terminated)
    pool = bytearray()
    pool_offsets: dict[str, int] = {}

    def intern(s: str) -> int:
        if s not in pool_offsets:
            pool_offsets[s] = len(pool)
            pool.extend(s.encode("utf-8") + b"\0")
        return pool_offsets[s]

    rule_entries = [
        (intern(r["title"]), intern(r["description"]), r["weight"])
        for r in comp.rules
    ]

    # patterns: flattened element sequences + rule lists
    elems: list[tuple[int, int, int]] = []
    pat_entries: list[tuple[int, int, int, int]] = []
    pat_rules: list[int] = []
    max_span = 1
    for pid, key in enumerate(comp.pattern_keys):
        elem_start = len(elems)
        span = 0
        for kind, a, b in key:
            elems.append((kind, a, b))
            span += b if kind == ELEM_GAP else (1 if kind != ELEM_PUNCT else 0)
        max_span = max(max_span, span)
        rules = sorted(comp.patterns[pid])
        pat_entries.append((elem_start, len(key), len(pat_rules), len(rules)))
        pat_rules.extend(rules)

    # start index: pattern ids grouped by their first element
    word_first: dict[int, list[int]] = {}
    prefix_first: dict[int, list[int]] = {}
    for pid, key in enumerate(comp.pattern_keys):
        kind, a, _ = key[0]
        d = word_first if kind == ELEM_WORD else prefix_first
        d.setdefault(a, []).append(pid)
    start_list: list[int] = []
    word_index: list[tuple[int, int]] = []
    for wid in range(len(comp.word_ids)):
        lst = word_first.get(wid, [])
        word_index.append((len(start_list), len(lst)))
        start_list.extend(lst)
    prefix_index: list[tuple[int, int]] = []
    for pid in range(len(comp.prefix_ids)):
        lst = prefix_first.get(pid, [])
        prefix_index.append((len(start_list), len(lst)))
        start_list.extend(lst)

    # --- assemble sections ---
    def align4(buf: bytearray) -> None:
        while len(buf) % 4:
            buf.append(0)

    body = bytearray(HEADER_SIZE)

    def section(fmt_items: bytes) -> int:
        align4(body)
        off = len(body)
        body.extend(fmt_items)
        return off

    rules_off = section(
        b"".join(struct.pack("<III", *e) for e in rule_entries)
    )
    strpool_off = section(bytes(pool) if pool else b"\0")
    strpool_size = len(pool) if pool else 1
    dat_base_off = section(struct.pack(f"<{len(base)}I", *base))
    dat_check_off = section(struct.pack(f"<{len(check)}I", *check))
    dat_wordid_off = section(struct.pack(f"<{len(wid_arr)}I", *wid_arr))
    dat_prefixid_off = section(struct.pack(f"<{len(pfx_arr)}I", *pfx_arr))
    pat_off = section(b"".join(struct.pack("<IIII", *e) for e in pat_entries))
    pat_rules_off = section(struct.pack(f"<{len(pat_rules)}I", *pat_rules))
    elems_off = section(b"".join(struct.pack("<III", *e) for e in elems))
    word_index_off = section(
        b"".join(struct.pack("<II", *e) for e in word_index)
    )
    prefix_index_off = section(
        b"".join(struct.pack("<II", *e) for e in prefix_index)
    )
    start_list_off = section(struct.pack(f"<{len(start_list)}I", *start_list))
    align4(body)

    header = struct.pack(
        "<4s" + "I" * 26 + "4s",
        MAGIC,
        VERSION,
        len(body),
        len(comp.rules),
        rules_off,
        strpool_off,
        strpool_size,
        len(base),
        dat_base_off,
        dat_check_off,
        dat_wordid_off,
        dat_prefixid_off,
        len(comp.word_ids),
        len(comp.prefix_ids),
        len(comp.patterns),
        pat_off,
        pat_rules_off,
        len(pat_rules),
        elems_off,
        len(elems),
        word_index_off,
        prefix_index_off,
        start_list_off,
        len(start_list),
        max_span,
        comp.comma_rule_id,
        comp.comma_threshold,
        comp.lang.encode("ascii").ljust(4, b"\0"),
    )
    assert len(header) == HEADER_SIZE, len(header)
    body[:HEADER_SIZE] = header

    comp.stats = {
        "rules": len(comp.rules),
        "words": len(comp.word_ids),
        "prefixes": len(comp.prefix_ids),
        "expanded_forms": comp.form_count,
        "patterns": len(comp.patterns),
        "elements": len(elems),
        "dat_slots": len(base),
        "blob_bytes": len(body),
    }
    return bytes(body)
