"""Serialization of a compiled ruleset into the binary blob format."""
from pathlib import Path

import struct

from .compiler import Compiler
from .constants import (
    ELEM_ANY,
    ELEM_GAP,
    ELEM_LEXEME,
    ELEM_PREFIX,
    ELEM_PUNCT,
    ELEM_PUNCT_RUN,
    ELEM_WORD,
    HEADER_SIZE,
    MAGIC,
    NONE,
    NONE16,
    U16_MAX_ID,
    VERSION,
)
from .trie import Trie


C_HEADER = """\
/* Generated by scripts/compile_rules.py — do not edit by hand.
 * Regenerate with: python3 scripts/compile_rules.py
 */
#include "rdktr_internal.h"
"""

C_FOOTER = """\
const rdktr_embedded_ruleset rdktr_embedded_rulesets[] = {{
{entries}
}};

const size_t rdktr_embedded_ruleset_count = {count};
"""

def emit_c(blobs: list[tuple[str, bytes]], path: Path) -> None:
    parts = [C_HEADER]
    for lang, blob in blobs:
        rows = []
        for i in range(0, len(blob), 16):
            chunk = blob[i : i + 16]
            rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        parts.append(
            f"\n_Alignas(4) static const uint8_t rules_{lang}[] = {{\n"
            + "\n".join(rows)
            + "\n};\n"
        )
    entries = "\n".join(
        f'    {{"{lang}", rules_{lang}, sizeof(rules_{lang})}},' for lang, _ in blobs
    )
    parts.append("\n" + C_FOOTER.format(entries=entries, count=len(blobs)))
    path.write_text("".join(parts), encoding="utf-8")


def build_blob(comp: Compiler) -> bytes:
    """Serialize a filled Compiler into a binary blob; sets comp.stats."""
    # word trie: exact words and prefix stems share it
    trie = Trie()
    for word, wid in comp.word_ids.items():
        trie.insert_word(word, wid)
    for stem, pid in comp.prefix_ids.items():
        trie.insert_prefix(stem, pid)
    base, check, wid_arr, pfx_arr = trie.build_double_array()

    # self-check: every word and prefix must be reachable
    for word, wid in comp.word_ids.items():
        slot = Trie.lookup(base, check, word.encode("utf-8"))
        assert slot is not None and wid_arr[slot] == wid, f"DAT broken for {word!r}"
    for stem, pid in comp.prefix_ids.items():
        slot = Trie.lookup(base, check, stem.encode("utf-8"))
        assert slot is not None and pfx_arr[slot] == pid

    # string pool (deduplicated, NUL-terminated)
    pool = bytearray()
    pool_offsets: dict[str, int] = {}

    def intern(s: str) -> int:
        if s not in pool_offsets:
            pool_offsets[s] = len(pool)
            pool.extend(s.encode("utf-8") + b"\0")
        return pool_offsets[s]

    rule_entries = [
        (intern(r["title"]), intern(r["description"]), r["weight"])
        for r in comp.rules
    ]

    # lexeme sets: sorted word-id slices referenced by ELEM_LEXEME
    lexeme_index: list[tuple[int, int]] = []
    lexeme_words: list[int] = []
    for s in comp.lexeme_sets:
        lexeme_index.append((len(lexeme_words), len(s)))
        lexeme_words.extend(s)  # already sorted & deduplicated by lexeme_id()

    # patterns: flattened element sequences + rule lists
    elems: list[tuple[int, int, int]] = []
    pat_entries: list[tuple[int, int, int, int]] = []
    pat_rules: list[int] = []
    max_span = 1
    for pid, key in enumerate(comp.pattern_keys):
        elem_start = len(elems)
        span = 0
        for kind, a, b in key:
            elems.append((kind, a, b))
            if kind in (ELEM_GAP, ELEM_ANY):
                span += b
            elif kind not in (ELEM_PUNCT, ELEM_PUNCT_RUN):
                span += 1
        max_span = max(max_span, span)
        rules = sorted(comp.patterns[pid])
        pat_entries.append((elem_start, len(key), len(pat_rules), len(rules)))
        pat_rules.extend(rules)

    # start index: pattern ids grouped by the words that can begin them;
    # a lexeme-initial pattern is seeded by every member form. Punctuation-
    # initial patterns go into a flat list scanned on every punctuation char.
    word_first: dict[int, list[int]] = {}
    prefix_first: dict[int, list[int]] = {}
    punct_start: list[int] = []
    for pid, key in enumerate(comp.pattern_keys):
        kind, a, _ = key[0]
        if kind == ELEM_WORD:
            word_first.setdefault(a, []).append(pid)
        elif kind == ELEM_PREFIX:
            prefix_first.setdefault(a, []).append(pid)
        elif kind in (ELEM_PUNCT, ELEM_PUNCT_RUN):
            punct_start.append(pid)
        else:  # ELEM_LEXEME
            for wid in comp.lexeme_sets[a]:
                word_first.setdefault(wid, []).append(pid)
    start_list: list[int] = []
    word_index: list[tuple[int, int]] = []
    for wid in range(len(comp.word_ids)):
        lst = word_first.get(wid, [])
        word_index.append((len(start_list), len(lst)))
        start_list.extend(lst)
    prefix_index: list[tuple[int, int]] = []
    for pid in range(len(comp.prefix_ids)):
        lst = prefix_first.get(pid, [])
        prefix_index.append((len(start_list), len(lst)))
        start_list.extend(lst)

    # --- u16 range guards (hard errors, never silent truncation) ---
    def check_limit(name: str, value: int, limit: int) -> None:
        if value > limit:
            raise SystemExit(
                f"[{comp.lang}] blob format overflow: {name} = {value}"
                f" exceeds {limit}; the u16 format is out of headroom"
            )

    check_limit("dat_size", len(base), U16_MAX_ID)
    check_limit("max(dat_base)", max(base), 0xFFFF)
    check_limit("word_count", len(comp.word_ids), U16_MAX_ID)
    check_limit("prefix_count", len(comp.prefix_ids), U16_MAX_ID)
    check_limit("rule_count", len(comp.rules), 0xFFFF)
    check_limit("pattern_count", len(pat_entries), 0xFFFF)
    check_limit("element_count", len(elems), 0xFFFF)
    check_limit("pat_rules_count", len(pat_rules), 0xFFFF)
    check_limit("start_list_count", len(start_list), 0xFFFF)
    check_limit("lexeme_count", len(lexeme_index), 0xFFFF)
    check_limit("lexeme_words_count", len(lexeme_words), 0xFFFF)
    check_limit("punct_start_count", len(punct_start), 0xFFFF)
    for kind, a, b in elems:
        if kind in (ELEM_PUNCT, ELEM_PUNCT_RUN):
            check_limit("punct codepoint", a, 0xFFFF)

    def to16(values: list[int]) -> list[int]:
        return [NONE16 if v == NONE else v for v in values]

    # --- assemble sections ---
    def align4(buf: bytearray) -> None:
        while len(buf) % 4:
            buf.append(0)

    body = bytearray(HEADER_SIZE)

    def section(fmt_items: bytes) -> int:
        align4(body)
        off = len(body)
        body.extend(fmt_items)
        return off

    def u16s(values: list[int]) -> bytes:
        return struct.pack(f"<{len(values)}H", *values)

    rules_off = section(
        b"".join(struct.pack("<III", *e) for e in rule_entries)
    )
    strpool_off = section(bytes(pool) if pool else b"\0")
    strpool_size = len(pool) if pool else 1
    dat_base_off = section(u16s(base))
    dat_check_off = section(u16s(to16(check)))
    dat_wordid_off = section(u16s(to16(wid_arr)))
    dat_prefixid_off = section(u16s(to16(pfx_arr)))
    pat_off = section(b"".join(struct.pack("<HHHH", *e) for e in pat_entries))
    pat_rules_off = section(u16s(pat_rules))
    elems_off = section(b"".join(struct.pack("<HHH", *e) for e in elems))
    word_index_off = section(
        b"".join(struct.pack("<HH", *e) for e in word_index)
    )
    prefix_index_off = section(
        b"".join(struct.pack("<HH", *e) for e in prefix_index)
    )
    start_list_off = section(u16s(start_list))
    lexeme_index_off = section(
        b"".join(struct.pack("<HH", *e) for e in lexeme_index)
    )
    lexeme_words_off = section(u16s(lexeme_words))
    punct_start_off = section(u16s(punct_start))
    align4(body)

    header = struct.pack(
        "<4s" + "I" * 32 + "4s",
        MAGIC,
        VERSION,
        len(body),
        len(comp.rules),
        rules_off,
        strpool_off,
        strpool_size,
        len(base),
        dat_base_off,
        dat_check_off,
        dat_wordid_off,
        dat_prefixid_off,
        len(comp.word_ids),
        len(comp.prefix_ids),
        len(comp.patterns),
        pat_off,
        pat_rules_off,
        len(pat_rules),
        elems_off,
        len(elems),
        word_index_off,
        prefix_index_off,
        start_list_off,
        len(start_list),
        len(lexeme_index),
        lexeme_index_off,
        lexeme_words_off,
        len(lexeme_words),
        max_span,
        comp.comma_rule_id,
        comp.comma_threshold,
        punct_start_off,
        len(punct_start),
        comp.lang.encode("ascii").ljust(4, b"\0"),
    )
    assert len(header) == HEADER_SIZE, len(header)
    body[:HEADER_SIZE] = header

    comp.stats = {
        "rules": len(comp.rules),
        "words": len(comp.word_ids),
        "prefixes": len(comp.prefix_ids),
        "expanded_forms": comp.form_count,
        "lexemes": len(comp.lexeme_sets),
        "lexeme_words": len(lexeme_words),
        "patterns": len(comp.patterns),
        "elements": len(elems),
        "dat_slots": len(base),
        "blob_bytes": len(body),
    }
    return bytes(body)
