import { createHash } from "node:crypto";
import { readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
import type { Plugin } from "vite";

const RUNTIME_HOSTS = ["fonts.googleapis.com", "fonts.gstatic.com"];

function listFiles(dir: string, root = dir): string[] {
    const out: string[] = [];
    for (const name of readdirSync(dir)) {
        const full = join(dir, name);
        if (statSync(full).isDirectory()) out.push(...listFiles(full, root));
        else out.push(relative(root, full).split("\\").join("/"));
    }
    return out;
}

function renderServiceWorker(base: string, cache: string, precache: string[]): string {
    return `// Generated by vite-plugin-sw — do not edit by hand.
const CACHE = ${JSON.stringify(cache)};
const BASE = ${JSON.stringify(base)};
const SHELL = BASE + "index.html";
const PRECACHE = ${JSON.stringify(precache, null, 2)};
const RUNTIME_HOSTS = ${JSON.stringify(RUNTIME_HOSTS)};

self.addEventListener("install", (event) => {
    event.waitUntil(
        caches.open(CACHE)
            .then((cache) => cache.addAll(PRECACHE))
            .then(() => self.skipWaiting())
    );
});

self.addEventListener("activate", (event) => {
    event.waitUntil(
        caches.keys()
            .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
            .then(() => self.clients.claim())
    );
});

self.addEventListener("fetch", (event) => {
    const req = event.request;
    if (req.method !== "GET") return;
    const url = new URL(req.url);

    // HTML navigations: network-first so a new deploy is picked up immediately;
    // fall back to the precached shell when offline.
    if (req.mode === "navigate") {
        event.respondWith(
            fetch(req)
                .then((res) => {
                    const copy = res.clone();
                    caches.open(CACHE).then((cache) => cache.put(SHELL, copy));
                    return res;
                })
                .catch(() => caches.match(SHELL))
        );
        return;
    }

    // Google Fonts: stale-while-revalidate.
    if (RUNTIME_HOSTS.includes(url.hostname)) {
        event.respondWith(
            caches.open(CACHE).then((cache) =>
                cache.match(req).then((cached) => {
                    const network = fetch(req)
                        .then((res) => { cache.put(req, res.clone()); return res; })
                        .catch(() => cached);
                    return cached || network;
                })
            )
        );
        return;
    }

    // Same-origin hashed assets: cache-first (content-addressed, immutable).
    if (url.origin === self.location.origin) {
        event.respondWith(
            caches.match(req).then((cached) => cached || fetch(req).then((res) => {
                if (res.ok) {
                    const copy = res.clone();
                    caches.open(CACHE).then((cache) => cache.put(req, copy));
                }
                return res;
            }))
        );
    }
});
`;
}

export function serviceWorker(): Plugin {
    let base = "/";
    let publicDir: string | false = false;

    return {
        name: "rdktr:service-worker",
        apply: "build",
        configResolved(config) {
            base = config.base;
            publicDir = config.publicDir;
        },
        generateBundle(_options, bundle) {
            const urls = new Set<string>();
            urls.add(base + "index.html");
            for (const fileName of Object.keys(bundle)) {
                if (fileName === "sw.js") continue;
                urls.add(base + fileName);
            }
            if (publicDir) {
                for (const file of listFiles(publicDir)) urls.add(base + file);
            }

            const precache = [...urls].sort();
            const cache = "rdktr-" + createHash("sha256").update(precache.join("\n")).digest("hex").slice(0, 12);

            this.emitFile({
                type: "asset",
                fileName: "sw.js",
                source: renderServiceWorker(base, cache, precache),
            });
        },
    };
}
